---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: "Set Facts"
    set_fact:
      Ami: "{{ Ami | default('ami-00aa4671cbf840d82') }}"
      KeyName: "{{ KeyName | default('Windows_2014-12-07.OpenSSH') }}"
      Az1: "{{ Az1 | default('eu-central-1a') }}"
      Az2: "{{ Az2 | default('eu-central-1b') }}"
      ProvisioningMethod: "{{ ProvisioningMethod | default('Ansible') }}"
      OrchestrationMethod: "{{ OrchestrationMethod | default('None') }}"
      Region: "{{ Region | default('eu-central-1') }}"
  - name: 01. Create VPC
    include_tasks: 01.vpc.yml
  - name: 02. Create Public Subnets
    include_tasks: 02.public_subnets.yml
  - name: 03. Create Private Subnets
    include_tasks: 03.private_subnets.yml
  - name: 04. Create Security Groups
    include_tasks: 04.security_groups.yml
  - name: 05. Create Virtual Machines
    include_tasks: 05.virtual_machines.yml
  - name: 06. Create Load Balancers
    include_tasks: 06.load_balancers.yml
